spring:
  application:
    name: spends-helper
  data:
    mongodb:
      host: localhost
      port: 27017
      database: spehel

server:
  port: 8089
  servlet:
    context-path: /main-service

spehel:
  bank:
    monobank:
      url: ${SPEHEL_MONOBANK_URL:https://api.monobank.ua}
      xToken: ${SPEHEL_X_TOKEN:aaa}
      dollarBalanceBlack: ${SPEHEL_DOLLAR_BALANCE_BLACK:aaa}
      hrivnaBalanceWhite: ${SPEHEL_HRIVNA_BALANCE_WHITE:aaa}
      hrivnaBalanceBlack: ${SPEHEL_HRIVNA_BALANCE_BLACK:aaa}
  monthToStart: ${SPEHEL_START_TIME_POINT:3}
  redis:
    host: localhost
    port: 6379