package io.spehel.bank.domain.model;

public enum Category {

    PRIVATE, PRODUCTS, RESTAURANTS_AND_DELIVERY, ENTERTAINMENT, APARTMENT_AND_PUBLIC_SERVICE, DEBT_LOAN_INSTALLMENTS, DEPOSITS, NASTYA_SCHOOL, COFFEE,
    PHARMACY, MOBILE_CONNECTION, CASH_WITHDRAWAL, FOR_NASTYA, SUBSCRIPTIONS, MONEY_TRANSFER, DRIVEWAY, SALARY_AND_INCOME, OTHER;

    @Override
    public String toString() {
        return super.toString();
    }
}
